# Generated by Django 4.2.3 on 2023-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshopmodel',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
