# Generated by Django 4.2.3 on 2023-08-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_customer_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='post',
        ),
    ]
