# Generated by Django 4.2.3 on 2023-08-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_date_orderd_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshopmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
